version: '3.8'

services:
  # Хранилище секретов Vault
  vault:
    image: hashicorp/vault:latest
    container_name: vault-secrets
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_TOKEN}
      VAULT_ADDR: http://0.0.0.0:8200
      VAULT_API_ADDR: http://vault:8200
      VAULT_LOG_LEVEL: info
    ports:
      - "8200:8200"
    volumes:
      - vault_data:/vault/data
    networks:
      - ml-network
    cap_add:
      - IPC_LOCK
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    command: server -dev

  # Однократная загрузка секретов в Vault
  vault-init:
    image: hashicorp/vault:latest
    container_name: vault-init
    entrypoint: /bin/sh
    depends_on:
      vault:
        condition: service_healthy
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: ${VAULT_TOKEN}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    command:
      - -c
      - |
        vault kv put secret/database/credentials           DB_HOST=postgres           DB_PORT=5432           DB_USER="$$DB_USER"           DB_PASSWORD="$$DB_PASSWORD"           DB_NAME="$$DB_NAME"
    networks:
      - ml-network


  # База данных PostgreSQL
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ml-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    depends_on:
      vault:
        condition: service_healthy

  #  ML модель
  model-api:
    build: .
    container_name: imagenet-classifier
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: ${VAULT_TOKEN}
      USE_VAULT: ${USE_VAULT:-true}
    volumes:
      - ./models:/app/models
    networks:
      - ml-network
    restart: unless-stopped

networks:
  ml-network:
    driver: bridge

volumes:
  postgres_data:
  vault_data:
